BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS revenues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tipo TEXT NOT NULL,
  valor REAL NOT NULL,
  data_iso TEXT NOT NULL,
  recorrente INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS investments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  categoria TEXT NOT NULL,
  valor REAL NOT NULL,
  data_iso TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tipo_principal TEXT NOT NULL,
  subcategoria TEXT NOT NULL,
  valor REAL NOT NULL,
  data_iso TEXT NOT NULL
);

COMMIT;
